#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
LAUNCH_DOMAIN="gui/$(id -u)"
LAUNCH_AGENTS_DIR="$HOME/Library/LaunchAgents"
LOG_DIR="$ROOT_DIR/.agent/runtime-logs"
TNF_HOME="$HOME/.tnf"
LOCAL_ENV="$HOME/.tnf.local.env"
NODE_BIN="${TNF_NODE_BIN:-$(command -v node || true)}"
REDIS_BIN="${TNF_REDIS_SERVER_BIN:-$(command -v redis-server || true)}"
SMART_START="$ROOT_DIR/scripts/runtime/tnf-launchd-smart-start.sh"

api_env_files() {
  printf '%s:%s:%s:%s\n' \
    "$ROOT_DIR/.env" \
    "$ROOT_DIR/apps/api/.env" \
    "$ROOT_DIR/.env.local" \
    "$LOCAL_ENV"
}

xml_escape() {
  python3 -c 'import sys,html; print(html.escape(sys.stdin.read(), quote=True), end="")' <<<"$1"
}

ensure_dirs() {
  mkdir -p "$LAUNCH_AGENTS_DIR" "$LOG_DIR" "$TNF_HOME/bin" "$TNF_HOME/redis" "$TNF_HOME/logs"
  chmod +x "$SMART_START"
}

secret_value_ok() {
  local key="$1" min_len="$2"
  [[ -f "$LOCAL_ENV" ]] || return 1
  local line value
  line="$(grep -E "^${key}=" "$LOCAL_ENV" | tail -1 || true)"
  [[ -n "$line" ]] || return 1
  value="${line#*=}"
  value="${value%\"}"
  value="${value#\"}"
  [[ ${#value} -ge "$min_len" ]] || return 1
  [[ ! "$value" =~ ^(REPLACE_WITH|your-|change|changeme|default-secret) ]] || return 1
}

random_hex_32() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  elif [[ -n "$NODE_BIN" ]]; then
    "$NODE_BIN" -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
  else
    echo "ERROR: openssl or node required to generate local secrets" >&2
    exit 1
  fi
}

ensure_local_secret() {
  local key="$1" min_len="${2:-32}"
  umask 077
  touch "$LOCAL_ENV"
  chmod 600 "$LOCAL_ENV"
  if secret_value_ok "$key" "$min_len"; then
    return 0
  fi
  {
    printf '\n# Local-only TNF secret generated by tnf-local-launchd-services.sh %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    printf '%s=%s\n' "$key" "$(random_hex_32)"
  } >>"$LOCAL_ENV"
}

write_api_plist() {
  local label="$1" app_dir="$2" entrypoint="$3" port="$4" wait_tcp="${5:-}"
  local plist="$LAUNCH_AGENTS_DIR/$label.plist"
  local wait_block=""
  if [[ -n "$wait_tcp" ]]; then
    wait_block="    <key>TNF_LAUNCHD_WAIT_TCP</key>
    <string>$(xml_escape "$wait_tcp")</string>"
  fi
  cat >"$plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${SMART_START}</string>
    <string>${label}</string>
    <string>${app_dir}</string>
    <string>${NODE_BIN}</string>
    <string>${entrypoint}</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PORT</key>
    <string>${port}</string>
    <key>LOCAL_API_SERVICE_URL</key>
    <string>http://127.0.0.1:3002</string>
    <key>TNF_LAUNCHD_ENV_FILES</key>
    <string>$(api_env_files)</string>
${wait_block}
  </dict>
  <key>RunAtLoad</key>
  <true/>
  <key>StartInterval</key>
  <integer>300</integer>
  <key>WorkingDirectory</key>
  <string>${app_dir}</string>
  <key>StandardOutPath</key>
  <string>${LOG_DIR}/${label#com.thenewfuse.}.log</string>
  <key>StandardErrorPath</key>
  <string>${LOG_DIR}/${label#com.thenewfuse.}.log</string>
</dict>
</plist>
PLIST
  plutil -lint "$plist" >/dev/null
}

write_redis_conf() {
  cat >"$TNF_HOME/redis/redis.conf" <<CONF
bind 127.0.0.1 ::1
protected-mode yes
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 300
save ""
stop-writes-on-bgsave-error no
dir ${TNF_HOME}/redis
dbfilename dump.rdb
appendonly no
shutdown-on-sigterm nosave
logfile ${TNF_HOME}/logs/redis.log
daemonize no
maxmemory ${TNF_REDIS_MAXMEMORY:-256mb}
maxmemory-policy allkeys-lru
maxclients ${TNF_REDIS_MAXCLIENTS:-10000}
CONF
}

write_redis_plist() {
  [[ -n "$REDIS_BIN" && -x "$REDIS_BIN" ]] || {
    echo "redis-server not found; skipping Redis launchd service" >&2
    return 0
  }
  write_redis_conf
  local label="com.thenewfuse.redis-tnf-bus"
  local plist="$LAUNCH_AGENTS_DIR/$label.plist"
  cat >"$plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${REDIS_BIN}</string>
    <string>${TNF_HOME}/redis/redis.conf</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${TNF_HOME}/redis</string>
  <key>RunAtLoad</key>
  <true/>
  <key>StartInterval</key>
  <integer>300</integer>
  <key>StandardOutPath</key>
  <string>${TNF_HOME}/logs/redis-stdout.log</string>
  <key>StandardErrorPath</key>
  <string>${TNF_HOME}/logs/redis-stderr.log</string>
  <key>ProcessType</key>
  <string>Background</string>
</dict>
</plist>
PLIST
  plutil -lint "$plist" >/dev/null
}

write_voice_plist() {
  local label="com.tnf.voice-beam-watchdog"
  local plist="$LAUNCH_AGENTS_DIR/$label.plist"
  cat >"$plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${ROOT_DIR}/scripts/system/voice-beam-watchdog.sh</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${ROOT_DIR}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>HOME</key>
    <string>${HOME}</string>
    <key>PATH</key>
    <string>$(dirname "$NODE_BIN"):/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    <key>VOICEBRIDGE_PROJECT_ROOT</key>
    <string>${ROOT_DIR}</string>
    <key>VOICEBRIDGE_STATE_DIR</key>
    <string>${ROOT_DIR}/.voicebridge</string>
    <key>VOICEBRIDGE_PROFILE</key>
    <string>${VOICEBRIDGE_PROFILE:-main}</string>
    <key>VOICE_KWS_ALWAYS_ON</key>
    <string>${VOICE_KWS_ALWAYS_ON:-1}</string>
    <key>VOICE_RESPONSE_AUDIO_DEFAULT_ON</key>
    <string>${VOICE_RESPONSE_AUDIO_DEFAULT_ON:-0}</string>
    <key>RELAY_URL</key>
    <string>${TNF_RELAY_URL:-${RELAY_WS_URL:-${RELAY_URL:-ws://127.0.0.1:3000/ws}}}</string>
  </dict>
  <key>RunAtLoad</key>
  <true/>
  <key>StartInterval</key>
  <integer>60</integer>
  <key>StandardOutPath</key>
  <string>/tmp/voice_beam_watchdog.launchd.log</string>
  <key>StandardErrorPath</key>
  <string>/tmp/voice_beam_watchdog.launchd.err.log</string>
</dict>
</plist>
PLIST
  plutil -lint "$plist" >/dev/null
}

install() {
  [[ "$(uname -s)" == "Darwin" ]] || {
    echo "launchd services are macOS-only; use direct dev scripts on this platform" >&2
    exit 1
  }
  [[ -n "$NODE_BIN" && -x "$NODE_BIN" ]] || {
    echo "node not found" >&2
    exit 1
  }
  ensure_dirs
  ensure_local_secret JWT_SECRET 32
  ensure_local_secret A2A_SECRET_KEY 16
  write_api_plist \
    "com.thenewfuse.api-local" \
    "$ROOT_DIR/apps/api" \
    "$ROOT_DIR/apps/api/dist/main.js" \
    "3002"
  write_api_plist \
    "com.thenewfuse.api-gateway" \
    "$ROOT_DIR/apps/api-gateway" \
    "$ROOT_DIR/apps/api-gateway/dist/main.js" \
    "3001" \
    "127.0.0.1:3002"
  write_redis_plist
  write_voice_plist
  echo "installed local TNF launchd services"
}

wait_tcp() {
  local host="$1"
  local port="$2"
  local timeout="${3:-30}"
  local waited=0
  while (( waited < timeout )); do
    if command -v nc >/dev/null 2>&1; then
      nc -z "$host" "$port" >/dev/null 2>&1 && return 0
    else
      (exec 3<>"/dev/tcp/$host/$port") >/dev/null 2>&1 && return 0
    fi
    sleep 1
    waited=$((waited + 1))
  done
  return 1
}

start_label() {
  local label="$1"
  local plist="$LAUNCH_AGENTS_DIR/$label.plist"
  local attempt err load_err
  [[ -f "$plist" ]] || return 0
  if launchctl print "$LAUNCH_DOMAIN/$label" >/dev/null 2>&1; then
    launchctl enable "$LAUNCH_DOMAIN/$label" >/dev/null 2>&1 || true
    launchctl kickstart "$LAUNCH_DOMAIN/$label" >/dev/null 2>&1 || true
    return 0
  fi
  for attempt in 1 2 3 4 5; do
    if err="$(launchctl bootstrap "$LAUNCH_DOMAIN" "$plist" 2>&1)"; then
      launchctl enable "$LAUNCH_DOMAIN/$label" >/dev/null 2>&1 || true
      launchctl kickstart "$LAUNCH_DOMAIN/$label" >/dev/null 2>&1 || true
      return 0
    fi
    if load_err="$(launchctl load -w "$plist" 2>&1)"; then
      launchctl enable "$LAUNCH_DOMAIN/$label" >/dev/null 2>&1 || true
      launchctl kickstart "$LAUNCH_DOMAIN/$label" >/dev/null 2>&1 || true
      return 0
    fi
    sleep 1
  done
  echo "WARN: could not start $label: ${err:-bootstrap failed} ${load_err:-load failed}" >&2
  return 1
}

bootout_label() {
  local label="$1"
  launchctl bootout "$LAUNCH_DOMAIN/$label" >/dev/null 2>&1 || true
  sleep 0.5
  launchctl enable "$LAUNCH_DOMAIN/$label" >/dev/null 2>&1 || true
}

restart_label() {
  local label="$1"
  bootout_label "$label"
  start_label "$label"
}

start() {
  install
  start_label com.thenewfuse.redis-tnf-bus
  wait_tcp 127.0.0.1 6379 30 || echo "WARN: Redis did not accept TCP on 127.0.0.1:6379 yet" >&2
  start_label com.thenewfuse.api-local
  wait_tcp 127.0.0.1 3002 30 || echo "WARN: local API did not accept TCP on 127.0.0.1:3002 yet" >&2
  start_label com.thenewfuse.api-gateway
  start_label com.tnf.voice-beam-watchdog
  echo "started local TNF launchd services"
}

restart() {
  install
  for label in \
    com.tnf.voice-beam-watchdog \
    com.thenewfuse.api-gateway \
    com.thenewfuse.api-local \
    com.thenewfuse.redis-tnf-bus; do
    bootout_label "$label"
  done
  start_label com.thenewfuse.redis-tnf-bus
  wait_tcp 127.0.0.1 6379 30 || echo "WARN: Redis did not accept TCP on 127.0.0.1:6379 yet" >&2
  start_label com.thenewfuse.api-local
  wait_tcp 127.0.0.1 3002 30 || echo "WARN: local API did not accept TCP on 127.0.0.1:3002 yet" >&2
  start_label com.thenewfuse.api-gateway
  start_label com.tnf.voice-beam-watchdog
  echo "restarted local TNF launchd services"
}

stop() {
  for label in \
    com.tnf.voice-beam-watchdog \
    com.thenewfuse.api-gateway \
    com.thenewfuse.api-local \
    com.thenewfuse.redis-tnf-bus; do
    launchctl bootout "$LAUNCH_DOMAIN/$label" >/dev/null 2>&1 || true
  done
  echo "stopped local TNF launchd services"
}

status() {
  for label in \
    com.thenewfuse.redis-tnf-bus \
    com.thenewfuse.api-local \
    com.thenewfuse.api-gateway \
    com.tnf.voice-beam-watchdog; do
    echo "-- $label"
    launchctl print "$LAUNCH_DOMAIN/$label" 2>/dev/null | awk '/state =|runs =|last exit code|pid =|run interval|program =/ {print}' || echo "not-installed"
  done
}

case "${1:-}" in
  install) install ;;
  start) start ;;
  stop) stop ;;
  restart) restart ;;
  status) status ;;
  *) echo "Usage: $0 <install|start|stop|restart|status>"; exit 1 ;;
esac
