import { Injectable, Logger } from '@nestjs/common';
import { UnifiedRedisService } from '@the-new-fuse/infrastructure';
import { createHmac } from 'crypto';

/**
 * TNF Federated Identity Service
 *
 * Implements "ID# Encoding" and cryptographic attribution for the
 * Software 3.0 Agent Federation.
 */
@Injectable()
export class FederatedIdentityService {
  private readonly logger = new Logger(FederatedIdentityService.name);
  private readonly ALPHABET = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'; // Base58

  constructor(private readonly redisService: UnifiedRedisService) {}

  /**
   * Encodes a sequential ID into a compact, secure ID# string.
   * Format: ID#:<encoded_id>
   */
  async generateIdNumber(agentId: string): Promise<string> {
    const key = `tnf:identity:seq:${agentId}`;
    // Using increment to get a sequential number per agent
    const seq = await this.redisService.incr(key);

    // Encode using Base58 for compactness and visual distinction
    const encoded = this.encodeBase58(seq);
    const idNumber = `ID#:${encoded}`;

    this.logger.debug(`Generated identity for ${agentId}: ${idNumber} (seq: ${seq})`);
    return idNumber;
  }

  /**
   * Verifies the cryptographic attribution of an AI Wiki entry.
   * Ensures the entry was generated by the agent it claims.
   */
  verifyAttribution(
    agentId: string,
    idNumber: string,
    content: string,
    signature: string,
    secret: string
  ): boolean {
    const message = `${agentId}|${idNumber}|${createHmac('sha256', secret).update(content).digest('hex')}`;
    const expectedSignature = createHmac('sha256', secret).update(message).digest('hex');

    const isValid = signature === expectedSignature;
    if (!isValid) {
      this.logger.warn(`Attribution failure for ${agentId} (${idNumber})`);
    }
    return isValid;
  }

  /**
   * Base58 Encoding (Bitcoin style)
   */
  private encodeBase58(num: number): string {
    let encoded = '';
    let temp = num;
    while (num > 0) {
      const remainder = num % 58;
      encoded = this.ALPHABET[remainder] + encoded;
      num = Math.floor(num / 58);
    }
    return encoded || this.ALPHABET[0];
  }
}
