/**
 * Database Package - Drizzle ORM
 *
 * This package provides database access using Drizzle ORM.
 */

// =============================================================================
// DRIZZLE ORM EXPORTS
// =============================================================================

// Export Drizzle client, module, and schema
export {
  DRIZZLE_CLIENT,
  DrizzleModule as DatabaseModule,
  DrizzleModule,
  DrizzleService,
  db,
  queryClient,
  schema,
  type Database,
  type DrizzleClient,
  type DrizzleModuleOptions,
  type Transaction,
} from './drizzle.js';

export { DatabaseService } from './drizzle/database.service.js';

export * as drizzleSchema from './drizzle/schema.js';

export {
  agentCapabilityRegistry,
  agentDirectoryEntries,
  agentManagedAccountGrants,
  agentManagedAccounts,
  agentMetrics,
  agentNfts,
  agentOnboardingEvents,
  agentRegistrations,
  agents,
  authSessions,
  authorityGrants,
  authorityResidencyEnum,
  authorityRoleEnum,
  chatRoomParticipants,
  chatRooms,
  creditBalances,
  durableRunEvents,
  durableRuns,
  durableSchedules,
  durableTasks,
  fractionalShares,
  marketplaceCatalogItems,
  marketplaceListings,
  marketplaceOffers,
  messages,
  notifications,
  providerApiKeys,
  revenueDistributions,
  revenueStreams,
  tasks,
  usageRecords,
  usageTypeEnum,
  users,
  workflowExecutions,
  workflows,
  workspaceMembers,
  workspaces,
} from './drizzle/schema.js';

// Export Drizzle inferred types
export type {
  Agent,
  AgentManagedAccount,
  AgentManagedAccountGrant,
  AuthorityGrant,
  Chat,
  ChatMessage,
  Message,
  NewAgent,
  NewAgentManagedAccount,
  NewAgentManagedAccountGrant,
  NewAuthorityGrant,
  NewChat,
  NewChatMessage,
  NewMessage,
  NewTask,
  NewTaskExecution,
  NewUser,
  NewWallet,
  NewWorkflow,
  NewWorkflowExecution,
  NewWorkspace,
  NewWorkspaceMember,
  Task,
  TaskExecution,
  User,
  Wallet,
  Workflow,
  WorkflowExecution,
  Workspace,
  WorkspaceMember,
} from './drizzle/types.js';

export {
  AuthorityGrantIssuerService,
  ConfigurablePublicKeyResolver,
  DrizzleAgentApiGrantRepository,
  DrizzleAgentManagedAccountRepository,
  DrizzleAgentRepository,
  DrizzleAuditLogsRepository,
  DrizzleAuthorityGrantRepository,
  DrizzleChatRepository,
  DrizzleFeedbackRepository,
  DrizzleMarketplaceCatalogRepository,
  DrizzlePromptTemplateRepository,
  DrizzleProviderApiKeyRepository,
  DrizzleTaskRepository,
  DrizzleUserRepository,
  DrizzleWorkflowRepository,
  DrizzleWorkspaceMemberRepository,
  DrizzleWorkspaceRepository,
  InMemoryTrustRootProvider,
  agentNftRepository,
  agentPromptVersionRepository,
  defaultPublicKeyResolver,
  drizzleAgentApiGrantRepository,
  drizzleAgentManagedAccountRepository,
  drizzleAgentRepository,
  drizzleApiLogsRepository,
  drizzleAuditLogsRepository,
  drizzleAuthorityGrantRepository,
  drizzleChatRepository,
  drizzleFeedbackRepository,
  drizzleMarketplaceCatalogRepository,
  drizzlePromptTemplateRepository,
  drizzleProviderApiKeyRepository,
  drizzleTaskRepository,
  drizzleUserRepository,
  drizzleWorkflowRepository,
  drizzleWorkspaceMemberRepository,
  drizzleWorkspaceRepository,
  fractionalShareRepository,
  optimizationJobRepository,
  revenueDistributionRepository,
  revenueStreamRepository,
  validationDatasetRepository,
  workflowTopologyRepository,
  type AuditLogEntry,
  type AuditLogQuery,
  type AuthorityGrantIssuerOptions,
  type AuthorityPublicKeyResolver,
  type IssueGrantRequest,
  type IssueOperatorRootRequest,
  type RenewGrantRequest,
  type ResolveSubjectAuthorityOptions,
} from './drizzle/repositories.js';

export {
  AgentRepository,
  ChatMessageRepository,
  ChatRepository,
  TaskRepository,
  UserRepository,
  WorkflowExecutionRepository,
  WorkflowRepository,
} from './drizzle/compatibility.js';

export {
  and,
  asc,
  desc,
  eq,
  gt,
  gte,
  ilike,
  inArray,
  isNotNull,
  isNull,
  like,
  lt,
  lte,
  ne,
  not,
  notInArray,
  or,
  sql,
} from 'drizzle-orm';

export {
  agentStatusEnum,
  agentTypeEnum,
  taskPriorityEnum,
  taskStatusEnum,
  userRoleEnum,
  workflowExecutionStatusEnum,
  workflowStatusEnum,
} from './drizzle/schema.js';

export type {
  AgentStatus,
  AgentType,
  MarketplaceStatus,
  MessageRole,
  OfferStatus,
  TaskPriority,
  TaskStatus,
  TransactionStatus,
  UserRole,
  WalletType,
  WorkflowExecutionStatus,
  WorkflowStatus,
} from './drizzle/types.js';
