// Agent relationship graph export — regenerated 2026-07-25T19:27:36.317Z
// Axes: daccRole ⊥ platform ⊥ workerAction ⊥ batonHolder

MERGE (a:Agent {id: "agent-registry-manager"}) SET a += {"id":"agent-registry-manager","kind":"primary","cluster":"orchestration","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "agent-relationship-grapher"}) SET a += {"id":"agent-relationship-grapher","kind":"primary","cluster":"orchestration","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "agent-search-engine"}) SET a += {"id":"agent-search-engine","kind":"primary","cluster":"orchestration","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "agent-tagger"}) SET a += {"id":"agent-tagger","kind":"primary","cluster":"orchestration","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "content-calendar-orchestrator-agent"}) SET a += {"id":"content-calendar-orchestrator-agent","kind":"primary","cluster":"orchestration","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "gemini"}) SET a += {"id":"gemini","kind":"sub","cluster":"orchestration","daccRole":"worker","platform":"gemini","workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "inter-agentic-workflow-definer"}) SET a += {"id":"inter-agentic-workflow-definer","kind":"primary","cluster":"orchestration","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "interoperability-protocol-agent"}) SET a += {"id":"interoperability-protocol-agent","kind":"primary","cluster":"orchestration","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "orchestrator-agent"}) SET a += {"id":"orchestrator-agent","kind":"primary","cluster":"orchestration","daccRole":"worker","platform":null,"workerAction":"orchestrator","batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "orchestrator-agent-copy"}) SET a += {"id":"orchestrator-agent-copy","kind":"sub","cluster":"orchestration","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "master-clock-baton"}) SET a += {"id":"master-clock-baton","kind":"infra","cluster":"runtime-infra","daccRole":"orchestrator","platform":"master-clock","workerAction":null,"batonHolder":true,"batonIdentity":"ORCHESTRATOR-{timestamp}"};
MERGE (a:Agent {id: "antigravity-platform"}) SET a += {"id":"antigravity-platform","kind":"platform","cluster":"fulfillment","daccRole":"worker","platform":"antigravity","workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "personal-archaeology-integrity-team-orchestrator"}) SET a += {"id":"personal-archaeology-integrity-team-orchestrator","kind":"primary","cluster":"orchestration","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "personal-archaeology-master-orchestrator"}) SET a += {"id":"personal-archaeology-master-orchestrator","kind":"primary","cluster":"orchestration","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "personal-archaeology-narrative-team-orchestrator"}) SET a += {"id":"personal-archaeology-narrative-team-orchestrator","kind":"primary","cluster":"orchestration","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "personal-archaeology-source-team-orchestrator"}) SET a += {"id":"personal-archaeology-source-team-orchestrator","kind":"primary","cluster":"orchestration","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "personal-historical-archaeologist"}) SET a += {"id":"personal-historical-archaeologist","kind":"sub","cluster":"orchestration","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "print-on-demand-manager-agent"}) SET a += {"id":"print-on-demand-manager-agent","kind":"sub","cluster":"orchestration","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "task-agent-router"}) SET a += {"id":"task-agent-router","kind":"primary","cluster":"orchestration","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "ad-network-manager-agent"}) SET a += {"id":"ad-network-manager-agent","kind":"primary","cluster":"content","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "analytics-and-reporting-agent"}) SET a += {"id":"analytics-and-reporting-agent","kind":"primary","cluster":"content","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "content-writer-agent"}) SET a += {"id":"content-writer-agent","kind":"primary","cluster":"content","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "digital-product-creator-agent"}) SET a += {"id":"digital-product-creator-agent","kind":"primary","cluster":"content","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "digital-product-factory-agent"}) SET a += {"id":"digital-product-factory-agent","kind":"primary","cluster":"content","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "fan-funding-agent"}) SET a += {"id":"fan-funding-agent","kind":"sub","cluster":"content","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "live-stream-manager-agent"}) SET a += {"id":"live-stream-manager-agent","kind":"sub","cluster":"content","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "media-evidence-investigator"}) SET a += {"id":"media-evidence-investigator","kind":"primary","cluster":"content","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "storyboard-artist-agent"}) SET a += {"id":"storyboard-artist-agent","kind":"sub","cluster":"content","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "technical-setup-agent"}) SET a += {"id":"technical-setup-agent","kind":"sub","cluster":"content","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "twip-orchestration-bridge"}) SET a += {"id":"twip-orchestration-bridge","kind":"sub","cluster":"content","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "user-feedback-analysis-agent"}) SET a += {"id":"user-feedback-analysis-agent","kind":"sub","cluster":"content","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "video-editor-agent"}) SET a += {"id":"video-editor-agent","kind":"sub","cluster":"content","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "yt-niche-strategy-agent"}) SET a += {"id":"yt-niche-strategy-agent","kind":"primary","cluster":"content","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "content-calendar-agent"}) SET a += {"id":"content-calendar-agent","kind":"primary","cluster":"seo","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "content-refresh-agent"}) SET a += {"id":"content-refresh-agent","kind":"primary","cluster":"seo","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "keyword-research-agent"}) SET a += {"id":"keyword-research-agent","kind":"primary","cluster":"seo","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "link-building-agent"}) SET a += {"id":"link-building-agent","kind":"primary","cluster":"seo","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "seo-optimizer-agent"}) SET a += {"id":"seo-optimizer-agent","kind":"primary","cluster":"seo","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "technical-seo-auditor-agent"}) SET a += {"id":"technical-seo-auditor-agent","kind":"primary","cluster":"seo","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "yt-seo-optimizer-agent"}) SET a += {"id":"yt-seo-optimizer-agent","kind":"primary","cluster":"seo","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "algorithm-adaptation-agent"}) SET a += {"id":"algorithm-adaptation-agent","kind":"sub","cluster":"social","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "audience-growth-agent"}) SET a += {"id":"audience-growth-agent","kind":"primary","cluster":"social","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "audience-persona-architect-agent"}) SET a += {"id":"audience-persona-architect-agent","kind":"sub","cluster":"social","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "audience-segmentation-agent"}) SET a += {"id":"audience-segmentation-agent","kind":"sub","cluster":"social","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "community-engagement-agent"}) SET a += {"id":"community-engagement-agent","kind":"sub","cluster":"social","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "community-manager-agent"}) SET a += {"id":"community-manager-agent","kind":"primary","cluster":"social","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "content-repurposing-agent"}) SET a += {"id":"content-repurposing-agent","kind":"primary","cluster":"social","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "facebook-strategy-agent"}) SET a += {"id":"facebook-strategy-agent","kind":"sub","cluster":"social","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "instagram-strategy-agent"}) SET a += {"id":"instagram-strategy-agent","kind":"sub","cluster":"social","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "scout-llm-opportunities"}) SET a += {"id":"scout-llm-opportunities","kind":"sub","cluster":"social","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "scriptwriter-agent"}) SET a += {"id":"scriptwriter-agent","kind":"primary","cluster":"social","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "social-selling-agent"}) SET a += {"id":"social-selling-agent","kind":"sub","cluster":"social","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "tiktok-strategy-agent"}) SET a += {"id":"tiktok-strategy-agent","kind":"primary","cluster":"social","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "traffic-generation-agent"}) SET a += {"id":"traffic-generation-agent","kind":"primary","cluster":"social","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "x-strategy-agent"}) SET a += {"id":"x-strategy-agent","kind":"primary","cluster":"social","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "ab-testing-optimizer-agent"}) SET a += {"id":"ab-testing-optimizer-agent","kind":"primary","cluster":"funnel","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "affiliate-link-manager-agent"}) SET a += {"id":"affiliate-link-manager-agent","kind":"primary","cluster":"funnel","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "audio-recording-agent"}) SET a += {"id":"audio-recording-agent","kind":"sub","cluster":"funnel","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "code-fossil-investigator"}) SET a += {"id":"code-fossil-investigator","kind":"sub","cluster":"funnel","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "cognitive-bias-optimizer-agent"}) SET a += {"id":"cognitive-bias-optimizer-agent","kind":"sub","cluster":"funnel","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "cro-process-agent"}) SET a += {"id":"cro-process-agent","kind":"primary","cluster":"funnel","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "customer-journey-map-agent"}) SET a += {"id":"customer-journey-map-agent","kind":"sub","cluster":"funnel","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "ecom-platform-manager-agent"}) SET a += {"id":"ecom-platform-manager-agent","kind":"sub","cluster":"funnel","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "equipment-recommendation-agent"}) SET a += {"id":"equipment-recommendation-agent","kind":"sub","cluster":"funnel","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "ethical-bias-auditor-agent"}) SET a += {"id":"ethical-bias-auditor-agent","kind":"sub","cluster":"funnel","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "funnel-economics-analyst-agent"}) SET a += {"id":"funnel-economics-analyst-agent","kind":"sub","cluster":"funnel","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "information-retrieval-agent"}) SET a += {"id":"information-retrieval-agent","kind":"sub","cluster":"funnel","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "lead-capture-agent"}) SET a += {"id":"lead-capture-agent","kind":"primary","cluster":"funnel","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "lead-magnet-funnel-agent"}) SET a += {"id":"lead-magnet-funnel-agent","kind":"primary","cluster":"funnel","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "master-of-taxonomies"}) SET a += {"id":"master-of-taxonomies","kind":"sub","cluster":"funnel","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "monetization-strategy-agent"}) SET a += {"id":"monetization-strategy-agent","kind":"primary","cluster":"funnel","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "niche-analyst-agent"}) SET a += {"id":"niche-analyst-agent","kind":"sub","cluster":"funnel","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "oto-sequence-architect-agent"}) SET a += {"id":"oto-sequence-architect-agent","kind":"sub","cluster":"funnel","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "personalized-content-recommendation-agent"}) SET a += {"id":"personalized-content-recommendation-agent","kind":"primary","cluster":"funnel","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "sales-funnel-architect-agent"}) SET a += {"id":"sales-funnel-architect-agent","kind":"sub","cluster":"funnel","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "value-ladder-architect-agent"}) SET a += {"id":"value-ladder-architect-agent","kind":"primary","cluster":"funnel","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "visual-asset-creator-agent"}) SET a += {"id":"visual-asset-creator-agent","kind":"sub","cluster":"funnel","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "episode-planner-agent"}) SET a += {"id":"episode-planner-agent","kind":"sub","cluster":"podcast","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "guest-booking-agent"}) SET a += {"id":"guest-booking-agent","kind":"sub","cluster":"podcast","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "guest-relationship-manager-agent"}) SET a += {"id":"guest-relationship-manager-agent","kind":"primary","cluster":"podcast","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "podcast-ad-network-agent"}) SET a += {"id":"podcast-ad-network-agent","kind":"sub","cluster":"podcast","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "podcast-affiliate-agent"}) SET a += {"id":"podcast-affiliate-agent","kind":"primary","cluster":"podcast","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "podcast-analytics-agent"}) SET a += {"id":"podcast-analytics-agent","kind":"primary","cluster":"podcast","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "podcast-audio-editor-agent"}) SET a += {"id":"podcast-audio-editor-agent","kind":"sub","cluster":"podcast","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "podcast-distribution-agent"}) SET a += {"id":"podcast-distribution-agent","kind":"sub","cluster":"podcast","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "podcast-equipment-agent"}) SET a += {"id":"podcast-equipment-agent","kind":"sub","cluster":"podcast","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "podcast-format-designer-agent"}) SET a += {"id":"podcast-format-designer-agent","kind":"sub","cluster":"podcast","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "podcast-hosting-setup-agent"}) SET a += {"id":"podcast-hosting-setup-agent","kind":"sub","cluster":"podcast","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "podcast-monetization-strategy-agent"}) SET a += {"id":"podcast-monetization-strategy-agent","kind":"sub","cluster":"podcast","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "podcast-niche-analyst-agent"}) SET a += {"id":"podcast-niche-analyst-agent","kind":"primary","cluster":"podcast","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "podcast-promotion-agent"}) SET a += {"id":"podcast-promotion-agent","kind":"primary","cluster":"podcast","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "podcast-seo-agent"}) SET a += {"id":"podcast-seo-agent","kind":"primary","cluster":"podcast","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "podcast-video-editor-agent"}) SET a += {"id":"podcast-video-editor-agent","kind":"sub","cluster":"podcast","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "sponsorship-outreach-agent"}) SET a += {"id":"sponsorship-outreach-agent","kind":"primary","cluster":"podcast","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "brand-identity-agent"}) SET a += {"id":"brand-identity-agent","kind":"primary","cluster":"brand","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "brand-outreach-agent"}) SET a += {"id":"brand-outreach-agent","kind":"sub","cluster":"brand","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "brand-prospecting-agent"}) SET a += {"id":"brand-prospecting-agent","kind":"sub","cluster":"brand","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "campaign-execution-agent"}) SET a += {"id":"campaign-execution-agent","kind":"primary","cluster":"brand","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "campaign-reporting-agent"}) SET a += {"id":"campaign-reporting-agent","kind":"primary","cluster":"brand","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "competitive-intelligence-agent"}) SET a += {"id":"competitive-intelligence-agent","kind":"primary","cluster":"brand","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "contract-manager-agent"}) SET a += {"id":"contract-manager-agent","kind":"sub","cluster":"brand","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "deal-negotiator-agent"}) SET a += {"id":"deal-negotiator-agent","kind":"sub","cluster":"brand","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "email-marketing-automation-agent"}) SET a += {"id":"email-marketing-automation-agent","kind":"sub","cluster":"brand","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "financial-manager-agent"}) SET a += {"id":"financial-manager-agent","kind":"primary","cluster":"brand","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "influencer-media-kit-agent"}) SET a += {"id":"influencer-media-kit-agent","kind":"sub","cluster":"brand","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "influencer-niche-agent"}) SET a += {"id":"influencer-niche-agent","kind":"sub","cluster":"brand","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "personal-brand-architect-agent"}) SET a += {"id":"personal-brand-architect-agent","kind":"sub","cluster":"brand","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "platform-selection-agent"}) SET a += {"id":"platform-selection-agent","kind":"sub","cluster":"brand","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "reputation-management-agent"}) SET a += {"id":"reputation-management-agent","kind":"primary","cluster":"brand","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "talent-manager-agent"}) SET a += {"id":"talent-manager-agent","kind":"sub","cluster":"brand","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "yt-content-strategy-agent"}) SET a += {"id":"yt-content-strategy-agent","kind":"primary","cluster":"brand","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "asset-sourcer-agent"}) SET a += {"id":"asset-sourcer-agent","kind":"primary","cluster":"ops","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "auth-blocker-sentinel"}) SET a += {"id":"auth-blocker-sentinel","kind":"primary","cluster":"ops","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "digital-asset-manager-agent"}) SET a += {"id":"digital-asset-manager-agent","kind":"primary","cluster":"ops","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "legal-compliance-agent"}) SET a += {"id":"legal-compliance-agent","kind":"primary","cluster":"ops","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "local-ai-claude-code-cli"}) SET a += {"id":"local-ai-claude-code-cli","kind":"sub","cluster":"ops","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "local-ai-gemini-cli"}) SET a += {"id":"local-ai-gemini-cli","kind":"sub","cluster":"ops","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "notes-ledger-investigator"}) SET a += {"id":"notes-ledger-investigator","kind":"primary","cluster":"ops","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "productivity-and-burnout-prevention-agent"}) SET a += {"id":"productivity-and-burnout-prevention-agent","kind":"sub","cluster":"ops","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "repo-lineage-investigator"}) SET a += {"id":"repo-lineage-investigator","kind":"primary","cluster":"ops","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "tax-compliance-agent"}) SET a += {"id":"tax-compliance-agent","kind":"primary","cluster":"ops","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};
MERGE (a:Agent {id: "timeline-synthesis-investigator"}) SET a += {"id":"timeline-synthesis-investigator","kind":"sub","cluster":"ops","daccRole":null,"platform":null,"workerAction":null,"batonHolder":false,"batonIdentity":null};

MATCH (s:Agent {id: "ab-testing-optimizer-agent"}), (t:Agent {id: "analytics-and-reporting-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "ab-testing-optimizer-agent"}), (t:Agent {id: "analytics-and-reporting-agent"}) MERGE (s)-[:RELATED {relationType: "MEASURED_BY"}]->(t);
MATCH (s:Agent {id: "ab-testing-optimizer-agent"}), (t:Agent {id: "audience-growth-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "ab-testing-optimizer-agent"}), (t:Agent {id: "cognitive-bias-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "ab-testing-optimizer-agent"}), (t:Agent {id: "email-marketing-automation-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "ab-testing-optimizer-agent"}), (t:Agent {id: "lead-magnet-funnel-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "ab-testing-optimizer-agent"}), (t:Agent {id: "traffic-generation-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "ad-network-manager-agent"}), (t:Agent {id: "analytics-and-reporting-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "ad-network-manager-agent"}), (t:Agent {id: "ethical-bias-auditor-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "ad-network-manager-agent"}), (t:Agent {id: "user-feedback-analysis-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "ad-network-manager-agent"}), (t:Agent {id: "yt-niche-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "affiliate-link-manager-agent"}), (t:Agent {id: "ab-testing-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "affiliate-link-manager-agent"}), (t:Agent {id: "algorithm-adaptation-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "affiliate-link-manager-agent"}), (t:Agent {id: "audience-persona-architect-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "affiliate-link-manager-agent"}), (t:Agent {id: "brand-identity-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "agent-registry-manager"}), (t:Agent {id: "agent-search-engine"}) MERGE (s)-[:RELATED {relationType: "INDEXES_FOR"}]->(t);
MATCH (s:Agent {id: "agent-registry-manager"}), (t:Agent {id: "agent-tagger"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "agent-relationship-grapher"}), (t:Agent {id: "inter-agentic-workflow-definer"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "agent-relationship-grapher"}), (t:Agent {id: "orchestrator-agent"}) MERGE (s)-[:RELATED {relationType: "ANALYZES"}]->(t);
MATCH (s:Agent {id: "agent-search-engine"}), (t:Agent {id: "orchestrator-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "agent-tagger"}), (t:Agent {id: "agent-search-engine"}) MERGE (s)-[:RELATED {relationType: "ENRICHES"}]->(t);
MATCH (s:Agent {id: "agent-tagger"}), (t:Agent {id: "agent-search-engine"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "agent-tagger"}), (t:Agent {id: "interoperability-protocol-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "algorithm-adaptation-agent"}), (t:Agent {id: "digital-product-creator-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "algorithm-adaptation-agent"}), (t:Agent {id: "information-retrieval-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "algorithm-adaptation-agent"}), (t:Agent {id: "yt-niche-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "analytics-and-reporting-agent"}), (t:Agent {id: "content-refresh-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "analytics-and-reporting-agent"}), (t:Agent {id: "content-writer-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "analytics-and-reporting-agent"}), (t:Agent {id: "ethical-bias-auditor-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "analytics-and-reporting-agent"}), (t:Agent {id: "user-feedback-analysis-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "asset-sourcer-agent"}), (t:Agent {id: "auth-blocker-sentinel"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "asset-sourcer-agent"}), (t:Agent {id: "legal-compliance-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "asset-sourcer-agent"}), (t:Agent {id: "link-building-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "asset-sourcer-agent"}), (t:Agent {id: "productivity-and-burnout-prevention-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "asset-sourcer-agent"}), (t:Agent {id: "tax-compliance-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "asset-sourcer-agent"}), (t:Agent {id: "visual-asset-creator-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDS"}]->(t);
MATCH (s:Agent {id: "asset-sourcer-agent"}), (t:Agent {id: "visual-asset-creator-agent"}) MERGE (s)-[:RELATED {relationType: "SUPPLIES"}]->(t);
MATCH (s:Agent {id: "audience-growth-agent"}), (t:Agent {id: "campaign-reporting-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "audience-growth-agent"}), (t:Agent {id: "community-engagement-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "audience-growth-agent"}), (t:Agent {id: "community-manager-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "audience-growth-agent"}), (t:Agent {id: "competitive-intelligence-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "audience-growth-agent"}), (t:Agent {id: "facebook-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "audience-persona-architect-agent"}), (t:Agent {id: "brand-identity-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "audience-persona-architect-agent"}), (t:Agent {id: "brand-outreach-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "audience-persona-architect-agent"}), (t:Agent {id: "monetization-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "audience-segmentation-agent"}), (t:Agent {id: "customer-journey-map-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "audience-segmentation-agent"}), (t:Agent {id: "funnel-economics-analyst-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "audience-segmentation-agent"}), (t:Agent {id: "value-ladder-architect-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "audio-recording-agent"}), (t:Agent {id: "digital-asset-manager-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "audio-recording-agent"}), (t:Agent {id: "fan-funding-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "audio-recording-agent"}), (t:Agent {id: "podcast-ad-network-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "auth-blocker-sentinel"}), (t:Agent {id: "code-fossil-investigator"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "auth-blocker-sentinel"}), (t:Agent {id: "media-evidence-investigator"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "auth-blocker-sentinel"}), (t:Agent {id: "notes-ledger-investigator"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "auth-blocker-sentinel"}), (t:Agent {id: "personal-archaeology-master-orchestrator"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "brand-identity-agent"}), (t:Agent {id: "campaign-reporting-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "brand-identity-agent"}), (t:Agent {id: "competitive-intelligence-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "brand-identity-agent"}), (t:Agent {id: "digital-product-creator-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "brand-identity-agent"}), (t:Agent {id: "keyword-research-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "brand-outreach-agent"}), (t:Agent {id: "brand-prospecting-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "brand-outreach-agent"}), (t:Agent {id: "deal-negotiator-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDS"}]->(t);
MATCH (s:Agent {id: "brand-outreach-agent"}), (t:Agent {id: "deal-negotiator-agent"}) MERGE (s)-[:RELATED {relationType: "HANDOFF"}]->(t);
MATCH (s:Agent {id: "brand-outreach-agent"}), (t:Agent {id: "influencer-niche-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "brand-outreach-agent"}), (t:Agent {id: "personal-brand-architect-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "brand-prospecting-agent"}), (t:Agent {id: "brand-outreach-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDS"}]->(t);
MATCH (s:Agent {id: "brand-prospecting-agent"}), (t:Agent {id: "deal-negotiator-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "brand-prospecting-agent"}), (t:Agent {id: "influencer-niche-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "brand-prospecting-agent"}), (t:Agent {id: "personal-brand-architect-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "brand-prospecting-agent"}), (t:Agent {id: "platform-selection-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "campaign-execution-agent"}), (t:Agent {id: "campaign-reporting-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDS"}]->(t);
MATCH (s:Agent {id: "campaign-execution-agent"}), (t:Agent {id: "campaign-reporting-agent"}) MERGE (s)-[:RELATED {relationType: "HANDOFF"}]->(t);
MATCH (s:Agent {id: "campaign-execution-agent"}), (t:Agent {id: "content-calendar-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "campaign-execution-agent"}), (t:Agent {id: "deal-negotiator-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "campaign-execution-agent"}), (t:Agent {id: "financial-manager-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "campaign-execution-agent"}), (t:Agent {id: "legal-compliance-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "campaign-execution-agent"}), (t:Agent {id: "yt-content-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "campaign-reporting-agent"}), (t:Agent {id: "community-manager-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "campaign-reporting-agent"}), (t:Agent {id: "competitive-intelligence-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "campaign-reporting-agent"}), (t:Agent {id: "influencer-media-kit-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "campaign-reporting-agent"}), (t:Agent {id: "reputation-management-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "code-fossil-investigator"}), (t:Agent {id: "media-evidence-investigator"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "code-fossil-investigator"}), (t:Agent {id: "notes-ledger-investigator"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "code-fossil-investigator"}), (t:Agent {id: "repo-lineage-investigator"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "cognitive-bias-optimizer-agent"}), (t:Agent {id: "analytics-and-reporting-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "cognitive-bias-optimizer-agent"}), (t:Agent {id: "analytics-and-reporting-agent"}) MERGE (s)-[:RELATED {relationType: "MEASURED_BY"}]->(t);
MATCH (s:Agent {id: "cognitive-bias-optimizer-agent"}), (t:Agent {id: "email-marketing-automation-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "cognitive-bias-optimizer-agent"}), (t:Agent {id: "financial-manager-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "cognitive-bias-optimizer-agent"}), (t:Agent {id: "influencer-media-kit-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "cognitive-bias-optimizer-agent"}), (t:Agent {id: "visual-asset-creator-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "community-engagement-agent"}), (t:Agent {id: "algorithm-adaptation-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "community-engagement-agent"}), (t:Agent {id: "community-manager-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "community-engagement-agent"}), (t:Agent {id: "competitive-intelligence-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "community-engagement-agent"}), (t:Agent {id: "instagram-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "community-manager-agent"}), (t:Agent {id: "podcast-promotion-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "community-manager-agent"}), (t:Agent {id: "social-selling-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "community-manager-agent"}), (t:Agent {id: "traffic-generation-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "competitive-intelligence-agent"}), (t:Agent {id: "brand-identity-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "competitive-intelligence-agent"}), (t:Agent {id: "monetization-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "competitive-intelligence-agent"}), (t:Agent {id: "talent-manager-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "competitive-intelligence-agent"}), (t:Agent {id: "traffic-generation-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "competitive-intelligence-agent"}), (t:Agent {id: "yt-niche-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "content-calendar-agent"}), (t:Agent {id: "content-writer-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "content-calendar-agent"}), (t:Agent {id: "episode-planner-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "content-calendar-agent"}), (t:Agent {id: "keyword-research-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "content-calendar-agent"}), (t:Agent {id: "seo-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "content-calendar-agent"}), (t:Agent {id: "technical-seo-auditor-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "content-calendar-orchestrator-agent"}), (t:Agent {id: "agent-relationship-grapher"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "content-calendar-orchestrator-agent"}), (t:Agent {id: "content-calendar-agent"}) MERGE (s)-[:RELATED {relationType: "OVERLAPS_WITH"}]->(t);
MATCH (s:Agent {id: "content-calendar-orchestrator-agent"}), (t:Agent {id: "ethical-bias-auditor-agent"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "content-calendar-orchestrator-agent"}), (t:Agent {id: "guest-relationship-manager-agent"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "content-calendar-orchestrator-agent"}), (t:Agent {id: "orchestrator-agent-copy"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "content-refresh-agent"}), (t:Agent {id: "keyword-research-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "content-refresh-agent"}), (t:Agent {id: "niche-analyst-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "content-refresh-agent"}), (t:Agent {id: "podcast-seo-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "content-refresh-agent"}), (t:Agent {id: "yt-seo-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "content-repurposing-agent"}), (t:Agent {id: "live-stream-manager-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "content-repurposing-agent"}), (t:Agent {id: "scriptwriter-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "content-repurposing-agent"}), (t:Agent {id: "tiktok-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "content-repurposing-agent"}), (t:Agent {id: "yt-seo-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "content-writer-agent"}), (t:Agent {id: "ad-network-manager-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "content-writer-agent"}), (t:Agent {id: "episode-planner-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "content-writer-agent"}), (t:Agent {id: "link-building-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "content-writer-agent"}), (t:Agent {id: "seo-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "content-writer-agent"}), (t:Agent {id: "seo-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDS"}]->(t);
MATCH (s:Agent {id: "content-writer-agent"}), (t:Agent {id: "seo-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "HANDOFF"}]->(t);
MATCH (s:Agent {id: "contract-manager-agent"}), (t:Agent {id: "brand-outreach-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "contract-manager-agent"}), (t:Agent {id: "campaign-execution-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "contract-manager-agent"}), (t:Agent {id: "campaign-execution-agent"}) MERGE (s)-[:RELATED {relationType: "GATES"}]->(t);
MATCH (s:Agent {id: "contract-manager-agent"}), (t:Agent {id: "customer-journey-map-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "contract-manager-agent"}), (t:Agent {id: "email-marketing-automation-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "contract-manager-agent"}), (t:Agent {id: "legal-compliance-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "contract-manager-agent"}), (t:Agent {id: "tax-compliance-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "cro-process-agent"}), (t:Agent {id: "ab-testing-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "cro-process-agent"}), (t:Agent {id: "ab-testing-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "ORCHESTRATES"}]->(t);
MATCH (s:Agent {id: "cro-process-agent"}), (t:Agent {id: "affiliate-link-manager-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "cro-process-agent"}), (t:Agent {id: "cognitive-bias-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "cro-process-agent"}), (t:Agent {id: "cognitive-bias-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "ORCHESTRATES"}]->(t);
MATCH (s:Agent {id: "cro-process-agent"}), (t:Agent {id: "customer-journey-map-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "cro-process-agent"}), (t:Agent {id: "funnel-economics-analyst-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "customer-journey-map-agent"}), (t:Agent {id: "funnel-economics-analyst-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "customer-journey-map-agent"}), (t:Agent {id: "tax-compliance-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "customer-journey-map-agent"}), (t:Agent {id: "value-ladder-architect-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "deal-negotiator-agent"}), (t:Agent {id: "contract-manager-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "deal-negotiator-agent"}), (t:Agent {id: "contract-manager-agent"}) MERGE (s)-[:RELATED {relationType: "REQUIRES"}]->(t);
MATCH (s:Agent {id: "deal-negotiator-agent"}), (t:Agent {id: "email-marketing-automation-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "deal-negotiator-agent"}), (t:Agent {id: "financial-manager-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "deal-negotiator-agent"}), (t:Agent {id: "personal-brand-architect-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "deal-negotiator-agent"}), (t:Agent {id: "sales-funnel-architect-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "digital-asset-manager-agent"}), (t:Agent {id: "auth-blocker-sentinel"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "digital-asset-manager-agent"}), (t:Agent {id: "fan-funding-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "digital-asset-manager-agent"}), (t:Agent {id: "podcast-ad-network-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "digital-asset-manager-agent"}), (t:Agent {id: "podcast-audio-editor-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "digital-asset-manager-agent"}), (t:Agent {id: "tax-compliance-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "digital-product-creator-agent"}), (t:Agent {id: "keyword-research-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "digital-product-creator-agent"}), (t:Agent {id: "link-building-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "digital-product-creator-agent"}), (t:Agent {id: "niche-analyst-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "digital-product-creator-agent"}), (t:Agent {id: "video-editor-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "digital-product-factory-agent"}), (t:Agent {id: "media-evidence-investigator"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "digital-product-factory-agent"}), (t:Agent {id: "niche-analyst-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "digital-product-factory-agent"}), (t:Agent {id: "seo-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "digital-product-factory-agent"}), (t:Agent {id: "sponsorship-outreach-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "ecom-platform-manager-agent"}), (t:Agent {id: "local-ai-claude-code-cli"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "ecom-platform-manager-agent"}), (t:Agent {id: "local-ai-gemini-cli"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "ecom-platform-manager-agent"}), (t:Agent {id: "print-on-demand-manager-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "email-marketing-automation-agent"}), (t:Agent {id: "financial-manager-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "email-marketing-automation-agent"}), (t:Agent {id: "influencer-media-kit-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "email-marketing-automation-agent"}), (t:Agent {id: "lead-capture-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "episode-planner-agent"}), (t:Agent {id: "equipment-recommendation-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "episode-planner-agent"}), (t:Agent {id: "podcast-equipment-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "episode-planner-agent"}), (t:Agent {id: "seo-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDS"}]->(t);
MATCH (s:Agent {id: "equipment-recommendation-agent"}), (t:Agent {id: "podcast-equipment-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "equipment-recommendation-agent"}), (t:Agent {id: "scriptwriter-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "equipment-recommendation-agent"}), (t:Agent {id: "seo-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "ethical-bias-auditor-agent"}), (t:Agent {id: "lead-magnet-funnel-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "ethical-bias-auditor-agent"}), (t:Agent {id: "user-feedback-analysis-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "ethical-bias-auditor-agent"}), (t:Agent {id: "visual-asset-creator-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "facebook-strategy-agent"}), (t:Agent {id: "instagram-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "facebook-strategy-agent"}), (t:Agent {id: "social-selling-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "facebook-strategy-agent"}), (t:Agent {id: "tiktok-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "facebook-strategy-agent"}), (t:Agent {id: "yt-seo-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDS"}]->(t);
MATCH (s:Agent {id: "fan-funding-agent"}), (t:Agent {id: "podcast-ad-network-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "fan-funding-agent"}), (t:Agent {id: "podcast-audio-editor-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "fan-funding-agent"}), (t:Agent {id: "podcast-hosting-setup-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "financial-manager-agent"}), (t:Agent {id: "brand-identity-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "financial-manager-agent"}), (t:Agent {id: "competitive-intelligence-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "financial-manager-agent"}), (t:Agent {id: "funnel-economics-analyst-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "financial-manager-agent"}), (t:Agent {id: "influencer-media-kit-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "financial-manager-agent"}), (t:Agent {id: "oto-sequence-architect-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "funnel-economics-analyst-agent"}), (t:Agent {id: "influencer-media-kit-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "funnel-economics-analyst-agent"}), (t:Agent {id: "lead-capture-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "funnel-economics-analyst-agent"}), (t:Agent {id: "oto-sequence-architect-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "guest-booking-agent"}), (t:Agent {id: "guest-relationship-manager-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDS"}]->(t);
MATCH (s:Agent {id: "guest-booking-agent"}), (t:Agent {id: "sponsorship-outreach-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "guest-booking-agent"}), (t:Agent {id: "talent-manager-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDS"}]->(t);
MATCH (s:Agent {id: "guest-relationship-manager-agent"}), (t:Agent {id: "link-building-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "guest-relationship-manager-agent"}), (t:Agent {id: "personalized-content-recommendation-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "guest-relationship-manager-agent"}), (t:Agent {id: "podcast-analytics-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "guest-relationship-manager-agent"}), (t:Agent {id: "podcast-distribution-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "influencer-media-kit-agent"}), (t:Agent {id: "lead-capture-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "influencer-media-kit-agent"}), (t:Agent {id: "oto-sequence-architect-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "influencer-media-kit-agent"}), (t:Agent {id: "sponsorship-outreach-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "influencer-niche-agent"}), (t:Agent {id: "personal-brand-architect-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "influencer-niche-agent"}), (t:Agent {id: "platform-selection-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "influencer-niche-agent"}), (t:Agent {id: "podcast-monetization-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "information-retrieval-agent"}), (t:Agent {id: "platform-selection-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "information-retrieval-agent"}), (t:Agent {id: "social-selling-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "information-retrieval-agent"}), (t:Agent {id: "yt-niche-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "instagram-strategy-agent"}), (t:Agent {id: "community-manager-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "instagram-strategy-agent"}), (t:Agent {id: "tiktok-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "instagram-strategy-agent"}), (t:Agent {id: "x-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "instagram-strategy-agent"}), (t:Agent {id: "yt-niche-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "interoperability-protocol-agent"}), (t:Agent {id: "agent-search-engine"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "interoperability-protocol-agent"}), (t:Agent {id: "local-ai-claude-code-cli"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "interoperability-protocol-agent"}), (t:Agent {id: "local-ai-gemini-cli"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "interoperability-protocol-agent"}), (t:Agent {id: "personal-archaeology-master-orchestrator"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "interoperability-protocol-agent"}), (t:Agent {id: "productivity-and-burnout-prevention-agent"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "keyword-research-agent"}), (t:Agent {id: "content-writer-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDS"}]->(t);
MATCH (s:Agent {id: "keyword-research-agent"}), (t:Agent {id: "link-building-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "keyword-research-agent"}), (t:Agent {id: "niche-analyst-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "keyword-research-agent"}), (t:Agent {id: "podcast-seo-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "keyword-research-agent"}), (t:Agent {id: "seo-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "lead-capture-agent"}), (t:Agent {id: "lead-magnet-funnel-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "lead-capture-agent"}), (t:Agent {id: "niche-analyst-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "lead-capture-agent"}), (t:Agent {id: "oto-sequence-architect-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "lead-capture-agent"}), (t:Agent {id: "sponsorship-outreach-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "lead-magnet-funnel-agent"}), (t:Agent {id: "personalized-content-recommendation-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "lead-magnet-funnel-agent"}), (t:Agent {id: "podcast-analytics-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "lead-magnet-funnel-agent"}), (t:Agent {id: "x-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "legal-compliance-agent"}), (t:Agent {id: "affiliate-link-manager-agent"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "legal-compliance-agent"}), (t:Agent {id: "affiliate-link-manager-agent"}) MERGE (s)-[:RELATED {relationType: "GOVERNS"}]->(t);
MATCH (s:Agent {id: "legal-compliance-agent"}), (t:Agent {id: "asset-sourcer-agent"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "legal-compliance-agent"}), (t:Agent {id: "asset-sourcer-agent"}) MERGE (s)-[:RELATED {relationType: "GOVERNS"}]->(t);
MATCH (s:Agent {id: "legal-compliance-agent"}), (t:Agent {id: "digital-asset-manager-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "legal-compliance-agent"}), (t:Agent {id: "link-building-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "legal-compliance-agent"}), (t:Agent {id: "tax-compliance-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "legal-compliance-agent"}), (t:Agent {id: "yt-niche-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "link-building-agent"}), (t:Agent {id: "content-refresh-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "link-building-agent"}), (t:Agent {id: "niche-analyst-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "link-building-agent"}), (t:Agent {id: "talent-manager-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "live-stream-manager-agent"}), (t:Agent {id: "personalized-content-recommendation-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "live-stream-manager-agent"}), (t:Agent {id: "video-editor-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "live-stream-manager-agent"}), (t:Agent {id: "yt-seo-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "local-ai-claude-code-cli"}), (t:Agent {id: "local-ai-gemini-cli"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "local-ai-claude-code-cli"}), (t:Agent {id: "productivity-and-burnout-prevention-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "local-ai-gemini-cli"}), (t:Agent {id: "podcast-ad-network-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "local-ai-gemini-cli"}), (t:Agent {id: "podcast-audio-editor-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "local-ai-gemini-cli"}), (t:Agent {id: "productivity-and-burnout-prevention-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "master-of-taxonomies"}), (t:Agent {id: "personal-archaeology-source-team-orchestrator"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "master-of-taxonomies"}), (t:Agent {id: "personal-historical-archaeologist"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "media-evidence-investigator"}), (t:Agent {id: "digital-product-creator-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "media-evidence-investigator"}), (t:Agent {id: "notes-ledger-investigator"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "media-evidence-investigator"}), (t:Agent {id: "repo-lineage-investigator"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "media-evidence-investigator"}), (t:Agent {id: "timeline-synthesis-investigator"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "monetization-strategy-agent"}), (t:Agent {id: "lead-capture-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "monetization-strategy-agent"}), (t:Agent {id: "platform-selection-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "monetization-strategy-agent"}), (t:Agent {id: "scriptwriter-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDS"}]->(t);
MATCH (s:Agent {id: "monetization-strategy-agent"}), (t:Agent {id: "yt-content-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "niche-analyst-agent"}), (t:Agent {id: "code-fossil-investigator"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "niche-analyst-agent"}), (t:Agent {id: "podcast-seo-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "niche-analyst-agent"}), (t:Agent {id: "seo-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDS"}]->(t);
MATCH (s:Agent {id: "niche-analyst-agent"}), (t:Agent {id: "yt-niche-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "notes-ledger-investigator"}), (t:Agent {id: "personal-archaeology-master-orchestrator"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "notes-ledger-investigator"}), (t:Agent {id: "repo-lineage-investigator"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "notes-ledger-investigator"}), (t:Agent {id: "timeline-synthesis-investigator"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "orchestrator-agent"}), (t:Agent {id: "agent-registry-manager"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "orchestrator-agent"}), (t:Agent {id: "agent-relationship-grapher"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "orchestrator-agent"}), (t:Agent {id: "agent-search-engine"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "orchestrator-agent"}), (t:Agent {id: "agent-tagger"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "orchestrator-agent"}), (t:Agent {id: "content-calendar-orchestrator-agent"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "orchestrator-agent"}), (t:Agent {id: "content-calendar-orchestrator-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "orchestrator-agent"}), (t:Agent {id: "gemini"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "orchestrator-agent"}), (t:Agent {id: "inter-agentic-workflow-definer"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "orchestrator-agent"}), (t:Agent {id: "interoperability-protocol-agent"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "orchestrator-agent"}), (t:Agent {id: "orchestrator-agent-copy"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "orchestrator-agent"}), (t:Agent {id: "personal-archaeology-integrity-team-orchestrator"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "orchestrator-agent"}), (t:Agent {id: "personal-archaeology-master-orchestrator"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "orchestrator-agent"}), (t:Agent {id: "personal-archaeology-narrative-team-orchestrator"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "orchestrator-agent"}), (t:Agent {id: "personal-archaeology-source-team-orchestrator"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "orchestrator-agent"}), (t:Agent {id: "personal-archaeology-source-team-orchestrator"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "orchestrator-agent"}), (t:Agent {id: "personal-historical-archaeologist"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "orchestrator-agent"}), (t:Agent {id: "print-on-demand-manager-agent"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "orchestrator-agent"}), (t:Agent {id: "task-agent-router"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "oto-sequence-architect-agent"}), (t:Agent {id: "reputation-management-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "oto-sequence-architect-agent"}), (t:Agent {id: "value-ladder-architect-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "personal-archaeology-integrity-team-orchestrator"}), (t:Agent {id: "personal-archaeology-master-orchestrator"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "personal-archaeology-integrity-team-orchestrator"}), (t:Agent {id: "personal-archaeology-narrative-team-orchestrator"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "personal-archaeology-integrity-team-orchestrator"}), (t:Agent {id: "personal-archaeology-source-team-orchestrator"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "personal-archaeology-master-orchestrator"}), (t:Agent {id: "personal-archaeology-integrity-team-orchestrator"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "personal-archaeology-master-orchestrator"}), (t:Agent {id: "personal-archaeology-narrative-team-orchestrator"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "personal-archaeology-master-orchestrator"}), (t:Agent {id: "personal-archaeology-source-team-orchestrator"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "personal-archaeology-master-orchestrator"}), (t:Agent {id: "personal-historical-archaeologist"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "personal-archaeology-narrative-team-orchestrator"}), (t:Agent {id: "personal-archaeology-source-team-orchestrator"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "personal-archaeology-narrative-team-orchestrator"}), (t:Agent {id: "personal-historical-archaeologist"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "personal-archaeology-narrative-team-orchestrator"}), (t:Agent {id: "repo-lineage-investigator"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "personal-archaeology-source-team-orchestrator"}), (t:Agent {id: "interoperability-protocol-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "personal-archaeology-source-team-orchestrator"}), (t:Agent {id: "personal-archaeology-master-orchestrator"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "personal-archaeology-source-team-orchestrator"}), (t:Agent {id: "personal-historical-archaeologist"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "personal-archaeology-source-team-orchestrator"}), (t:Agent {id: "repo-lineage-investigator"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "personal-archaeology-source-team-orchestrator"}), (t:Agent {id: "timeline-synthesis-investigator"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "personal-brand-architect-agent"}), (t:Agent {id: "platform-selection-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "personal-brand-architect-agent"}), (t:Agent {id: "podcast-affiliate-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "personal-brand-architect-agent"}), (t:Agent {id: "podcast-monetization-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "personal-historical-archaeologist"}), (t:Agent {id: "repo-lineage-investigator"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "personal-historical-archaeologist"}), (t:Agent {id: "timeline-synthesis-investigator"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "personalized-content-recommendation-agent"}), (t:Agent {id: "monetization-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "personalized-content-recommendation-agent"}), (t:Agent {id: "podcast-analytics-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "personalized-content-recommendation-agent"}), (t:Agent {id: "podcast-seo-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "personalized-content-recommendation-agent"}), (t:Agent {id: "tiktok-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "platform-selection-agent"}), (t:Agent {id: "scriptwriter-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "platform-selection-agent"}), (t:Agent {id: "yt-content-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-ad-network-agent"}), (t:Agent {id: "podcast-audio-editor-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-ad-network-agent"}), (t:Agent {id: "podcast-hosting-setup-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-ad-network-agent"}), (t:Agent {id: "storyboard-artist-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "podcast-affiliate-agent"}), (t:Agent {id: "podcast-monetization-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-affiliate-agent"}), (t:Agent {id: "podcast-niche-analyst-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-affiliate-agent"}), (t:Agent {id: "podcast-video-editor-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-affiliate-agent"}), (t:Agent {id: "sponsorship-outreach-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-analytics-agent"}), (t:Agent {id: "podcast-hosting-setup-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-analytics-agent"}), (t:Agent {id: "podcast-niche-analyst-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-analytics-agent"}), (t:Agent {id: "podcast-video-editor-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-analytics-agent"}), (t:Agent {id: "sponsorship-outreach-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-audio-editor-agent"}), (t:Agent {id: "podcast-hosting-setup-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-audio-editor-agent"}), (t:Agent {id: "storyboard-artist-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "podcast-audio-editor-agent"}), (t:Agent {id: "video-editor-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "podcast-distribution-agent"}), (t:Agent {id: "podcast-promotion-agent"}) MERGE (s)-[:RELATED {relationType: "ENABLES"}]->(t);
MATCH (s:Agent {id: "podcast-distribution-agent"}), (t:Agent {id: "podcast-promotion-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDS"}]->(t);
MATCH (s:Agent {id: "podcast-distribution-agent"}), (t:Agent {id: "scout-llm-opportunities"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "podcast-distribution-agent"}), (t:Agent {id: "sponsorship-outreach-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-equipment-agent"}), (t:Agent {id: "podcast-format-designer-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-equipment-agent"}), (t:Agent {id: "podcast-monetization-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-equipment-agent"}), (t:Agent {id: "twip-orchestration-bridge"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "podcast-format-designer-agent"}), (t:Agent {id: "guest-relationship-manager-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-format-designer-agent"}), (t:Agent {id: "podcast-hosting-setup-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDS"}]->(t);
MATCH (s:Agent {id: "podcast-format-designer-agent"}), (t:Agent {id: "podcast-hosting-setup-agent"}) MERGE (s)-[:RELATED {relationType: "HANDOFF"}]->(t);
MATCH (s:Agent {id: "podcast-format-designer-agent"}), (t:Agent {id: "storyboard-artist-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "podcast-format-designer-agent"}), (t:Agent {id: "twip-orchestration-bridge"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "podcast-hosting-setup-agent"}), (t:Agent {id: "podcast-distribution-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDS"}]->(t);
MATCH (s:Agent {id: "podcast-hosting-setup-agent"}), (t:Agent {id: "podcast-distribution-agent"}) MERGE (s)-[:RELATED {relationType: "HANDOFF"}]->(t);
MATCH (s:Agent {id: "podcast-hosting-setup-agent"}), (t:Agent {id: "podcast-format-designer-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-hosting-setup-agent"}), (t:Agent {id: "storyboard-artist-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "podcast-hosting-setup-agent"}), (t:Agent {id: "video-editor-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDS"}]->(t);
MATCH (s:Agent {id: "podcast-monetization-strategy-agent"}), (t:Agent {id: "podcast-niche-analyst-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-monetization-strategy-agent"}), (t:Agent {id: "scriptwriter-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDS"}]->(t);
MATCH (s:Agent {id: "podcast-niche-analyst-agent"}), (t:Agent {id: "podcast-format-designer-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDS"}]->(t);
MATCH (s:Agent {id: "podcast-niche-analyst-agent"}), (t:Agent {id: "podcast-hosting-setup-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-niche-analyst-agent"}), (t:Agent {id: "podcast-seo-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-niche-analyst-agent"}), (t:Agent {id: "podcast-video-editor-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDS"}]->(t);
MATCH (s:Agent {id: "podcast-niche-analyst-agent"}), (t:Agent {id: "scriptwriter-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDS"}]->(t);
MATCH (s:Agent {id: "podcast-niche-analyst-agent"}), (t:Agent {id: "sponsorship-outreach-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-promotion-agent"}), (t:Agent {id: "guest-relationship-manager-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-promotion-agent"}), (t:Agent {id: "podcast-analytics-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "podcast-promotion-agent"}), (t:Agent {id: "podcast-analytics-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-promotion-agent"}), (t:Agent {id: "podcast-analytics-agent"}) MERGE (s)-[:RELATED {relationType: "MEASURED_BY"}]->(t);
MATCH (s:Agent {id: "podcast-promotion-agent"}), (t:Agent {id: "reputation-management-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "podcast-promotion-agent"}), (t:Agent {id: "sponsorship-outreach-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-promotion-agent"}), (t:Agent {id: "traffic-generation-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "podcast-seo-agent"}), (t:Agent {id: "podcast-affiliate-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-seo-agent"}), (t:Agent {id: "tiktok-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "podcast-seo-agent"}), (t:Agent {id: "yt-seo-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "podcast-video-editor-agent"}), (t:Agent {id: "episode-planner-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-video-editor-agent"}), (t:Agent {id: "sponsorship-outreach-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "podcast-video-editor-agent"}), (t:Agent {id: "video-editor-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "productivity-and-burnout-prevention-agent"}), (t:Agent {id: "digital-asset-manager-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "productivity-and-burnout-prevention-agent"}), (t:Agent {id: "talent-manager-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "repo-lineage-investigator"}), (t:Agent {id: "timeline-synthesis-investigator"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "reputation-management-agent"}), (t:Agent {id: "contract-manager-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "reputation-management-agent"}), (t:Agent {id: "social-selling-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "reputation-management-agent"}), (t:Agent {id: "x-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "reputation-management-agent"}), (t:Agent {id: "yt-content-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "sales-funnel-architect-agent"}), (t:Agent {id: "lead-magnet-funnel-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "sales-funnel-architect-agent"}), (t:Agent {id: "value-ladder-architect-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "scout-llm-opportunities"}), (t:Agent {id: "social-selling-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "scout-llm-opportunities"}), (t:Agent {id: "tax-compliance-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "scriptwriter-agent"}), (t:Agent {id: "tiktok-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "scriptwriter-agent"}), (t:Agent {id: "yt-content-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "seo-optimizer-agent"}), (t:Agent {id: "content-calendar-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "seo-optimizer-agent"}), (t:Agent {id: "technical-seo-auditor-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "seo-optimizer-agent"}), (t:Agent {id: "technical-seo-auditor-agent"}) MERGE (s)-[:RELATED {relationType: "VALIDATED_BY"}]->(t);
MATCH (s:Agent {id: "social-selling-agent"}), (t:Agent {id: "tax-compliance-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "sponsorship-outreach-agent"}), (t:Agent {id: "podcast-niche-analyst-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "sponsorship-outreach-agent"}), (t:Agent {id: "podcast-seo-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "sponsorship-outreach-agent"}), (t:Agent {id: "talent-manager-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "storyboard-artist-agent"}), (t:Agent {id: "video-editor-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "storyboard-artist-agent"}), (t:Agent {id: "visual-asset-creator-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "talent-manager-agent"}), (t:Agent {id: "brand-identity-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "agent-registry-manager"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "analytics-and-reporting-agent"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "audience-segmentation-agent"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "audio-recording-agent"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "campaign-execution-agent"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "campaign-execution-agent"}) MERGE (s)-[:RELATED {relationType: "ROUTES_TO"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "community-engagement-agent"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "community-manager-agent"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "content-calendar-agent"}) MERGE (s)-[:RELATED {relationType: "ROUTES_TO"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "content-calendar-orchestrator-agent"}) MERGE (s)-[:RELATED {relationType: "ROUTES_TO"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "content-repurposing-agent"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "content-writer-agent"}) MERGE (s)-[:RELATED {relationType: "ROUTES_TO"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "cro-process-agent"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "cro-process-agent"}) MERGE (s)-[:RELATED {relationType: "ROUTES_TO"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "ecom-platform-manager-agent"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "guest-booking-agent"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "keyword-research-agent"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "keyword-research-agent"}) MERGE (s)-[:RELATED {relationType: "ROUTES_TO"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "legal-compliance-agent"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "legal-compliance-agent"}) MERGE (s)-[:RELATED {relationType: "ROUTES_TO"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "master-of-taxonomies"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "podcast-promotion-agent"}) MERGE (s)-[:RELATED {relationType: "DELEGATES"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "podcast-promotion-agent"}) MERGE (s)-[:RELATED {relationType: "ROUTES_TO"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "seo-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "ROUTES_TO"}]->(t);
MATCH (s:Agent {id: "task-agent-router"}), (t:Agent {id: "technical-seo-auditor-agent"}) MERGE (s)-[:RELATED {relationType: "ROUTES_TO"}]->(t);
MATCH (s:Agent {id: "tax-compliance-agent"}), (t:Agent {id: "asset-sourcer-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "tax-compliance-agent"}), (t:Agent {id: "value-ladder-architect-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "technical-seo-auditor-agent"}), (t:Agent {id: "content-calendar-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDBACK"}]->(t);
MATCH (s:Agent {id: "technical-seo-auditor-agent"}), (t:Agent {id: "link-building-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "technical-seo-auditor-agent"}), (t:Agent {id: "technical-setup-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "technical-seo-auditor-agent"}), (t:Agent {id: "yt-seo-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "technical-setup-agent"}), (t:Agent {id: "user-feedback-analysis-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "technical-setup-agent"}), (t:Agent {id: "visual-asset-creator-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDS"}]->(t);
MATCH (s:Agent {id: "tiktok-strategy-agent"}), (t:Agent {id: "x-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "tiktok-strategy-agent"}), (t:Agent {id: "yt-seo-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDS"}]->(t);
MATCH (s:Agent {id: "timeline-synthesis-investigator"}), (t:Agent {id: "local-ai-gemini-cli"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "traffic-generation-agent"}), (t:Agent {id: "content-repurposing-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "traffic-generation-agent"}), (t:Agent {id: "scriptwriter-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "traffic-generation-agent"}), (t:Agent {id: "x-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "traffic-generation-agent"}), (t:Agent {id: "yt-content-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "user-feedback-analysis-agent"}), (t:Agent {id: "visual-asset-creator-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "value-ladder-architect-agent"}), (t:Agent {id: "sales-funnel-architect-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "video-editor-agent"}), (t:Agent {id: "fan-funding-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "visual-asset-creator-agent"}), (t:Agent {id: "value-ladder-architect-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "x-strategy-agent"}), (t:Agent {id: "audience-growth-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "x-strategy-agent"}), (t:Agent {id: "yt-content-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "x-strategy-agent"}), (t:Agent {id: "yt-niche-strategy-agent"}) MERGE (s)-[:RELATED {relationType: "DEPENDS_ON"}]->(t);
MATCH (s:Agent {id: "x-strategy-agent"}), (t:Agent {id: "yt-seo-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDS"}]->(t);
MATCH (s:Agent {id: "yt-content-strategy-agent"}), (t:Agent {id: "contract-manager-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "yt-niche-strategy-agent"}), (t:Agent {id: "digital-product-factory-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "yt-niche-strategy-agent"}), (t:Agent {id: "yt-seo-optimizer-agent"}) MERGE (s)-[:RELATED {relationType: "FEEDS"}]->(t);
MATCH (s:Agent {id: "yt-seo-optimizer-agent"}), (t:Agent {id: "link-building-agent"}) MERGE (s)-[:RELATED {relationType: "FALLBACK"}]->(t);
MATCH (s:Agent {id: "master-clock-baton"}), (t:Agent {id: "orchestrator-agent"}) MERGE (s)-[:RELATED {relationType: "GOVERNS"}]->(t);
MATCH (s:Agent {id: "master-clock-baton"}), (t:Agent {id: "agent-registry-manager"}) MERGE (s)-[:RELATED {relationType: "GOVERNS"}]->(t);
MATCH (s:Agent {id: "master-clock-baton"}), (t:Agent {id: "task-agent-router"}) MERGE (s)-[:RELATED {relationType: "GOVERNS"}]->(t);
