#!/usr/bin/env bash
#
# Materialize apps/frontend/.env.production for Vite production builds.
#
# .env.production is gitignored, so clean deploy worktrees and CI runners do not
# ship Supabase OAuth unless we synthesize it here from the repo root .env or
# from the caller's environment (Cloudflare/GCP secrets, operator shell, etc.).
#
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
frontend_dir="$repo_root/apps/frontend"
out="$frontend_dir/.env.production"

read_env_value() {
  local file="$1"
  local key="$2"
  [[ -f "$file" ]] || return 0
  local line
  line="$(grep -E "^${key}=" "$file" | tail -1 || true)"
  [[ -n "$line" ]] || return 0
  local val="${line#*=}"
  val="${val%$'\r'}"
  val="${val#"${val%%[![:space:]]*}"}"
  val="${val%"${val##*[![:space:]]}"}"
  val="${val#\"}"; val="${val%\"}"
  val="${val#\'}"; val="${val%\'}"
  printf '%s' "$val"
}

pick() {
  local key="$1"
  local from_env="${!key-}"
  if [[ -n "$from_env" ]]; then
    printf '%s' "$from_env"
    return
  fi
  local from_root
  from_root="$(read_env_value "$repo_root/.env" "$key")"
  if [[ -n "$from_root" ]]; then
    printf '%s' "$from_root"
    return
  fi
  local alt=""
  case "$key" in
    VITE_SUPABASE_URL) alt="SUPABASE_URL" ;;
    VITE_SUPABASE_ANON_KEY) alt="SUPABASE_ANON_KEY" ;;
  esac
  if [[ -n "$alt" ]]; then
    from_env="${!alt-}"
    if [[ -n "$from_env" ]]; then
      printf '%s' "$from_env"
      return
    fi
    from_root="$(read_env_value "$repo_root/.env" "$alt")"
    if [[ -n "$from_root" ]]; then
      printf '%s' "$from_root"
      return
    fi
  fi
  read_env_value "$frontend_dir/.env.production" "$key"
}

VITE_API_URL="$(pick VITE_API_URL)"
VITE_API_GATEWAY_URL="$(pick VITE_API_GATEWAY_URL)"
VITE_WS_URL="$(pick VITE_WS_URL)"
VITE_SUPABASE_URL="$(pick VITE_SUPABASE_URL)"
VITE_SUPABASE_ANON_KEY="$(pick VITE_SUPABASE_ANON_KEY)"
VITE_TURNSTILE_SITE_KEY="$(pick VITE_TURNSTILE_SITE_KEY)"
VITE_AUTH_REQUIRE_TURNSTILE="$(pick VITE_AUTH_REQUIRE_TURNSTILE)"
VITE_BASE_PATH="$(pick VITE_BASE_PATH)"

missing=()
[[ -n "$VITE_SUPABASE_URL" ]] || missing+=("VITE_SUPABASE_URL (or SUPABASE_URL)")
[[ -n "$VITE_SUPABASE_ANON_KEY" ]] || missing+=("VITE_SUPABASE_ANON_KEY (or SUPABASE_ANON_KEY)")

if [[ ${#missing[@]} -gt 0 ]]; then
  echo "ERROR: Frontend production build is missing Supabase auth env:" >&2
  for m in "${missing[@]}"; do echo "  - $m" >&2; done
  echo "Set them in the environment or in $repo_root/.env before deploying." >&2
  exit 1
fi

cat > "$out" <<EOF
# Generated by scripts/deployment/prepare-frontend-env.sh — do not commit
ENVIRONMENT=production

VITE_API_URL=${VITE_API_URL:-https://api.thenewfuse.com}
VITE_API_GATEWAY_URL=${VITE_API_GATEWAY_URL:-https://api.thenewfuse.com}
VITE_WS_URL=${VITE_WS_URL:-wss://relay.thenewfuse.com}

VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}

VITE_TURNSTILE_SITE_KEY=${VITE_TURNSTILE_SITE_KEY:-}
VITE_AUTH_REQUIRE_TURNSTILE=${VITE_AUTH_REQUIRE_TURNSTILE:-true}
VITE_BASE_PATH=${VITE_BASE_PATH:-/}
EOF

echo "Wrote $out (Supabase URL: ${VITE_SUPABASE_URL})"
